#!/bin/bash

echo 'Copying .zshrc'
cp .zshrc ~/.zshrc

echo 'Copying .gitconfig'
cp .gitconfig ~/.gitconfig
cp .gitconfig-work ~/.gitconfig-work

echo 'Copying .gitignore_global'
cp .gitignore_global ~/.gitignore_global

echo 'Copying sshconfig'
cp sshconfig ~/.ssh/config

echo 'Done'
